"""initial schema

Revision ID: 0d8089ce022e
Revises: 
Create Date: 2026-07-13 07:35:44.080380
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d8089ce022e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_users',
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_users_employee_code'), 'application_users', ['employee_code'], unique=True)
    op.create_table('equipment_templates',
    sa.Column('equipment_code', sa.String(length=64), nullable=True),
    sa.Column('equipment_description', sa.String(length=512), nullable=False),
    sa.Column('normalized_description', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_description', name='uq_equipment_normalized_desc')
    )
    op.create_index(op.f('ix_equipment_templates_equipment_code'), 'equipment_templates', ['equipment_code'], unique=False)
    op.create_index(op.f('ix_equipment_templates_normalized_description'), 'equipment_templates', ['normalized_description'], unique=False)
    op.create_table('equipment_aliases',
    sa.Column('equipment_template_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', name='uq_equipment_normalized_alias')
    )
    op.create_index(op.f('ix_equipment_aliases_equipment_template_id'), 'equipment_aliases', ['equipment_template_id'], unique=False)
    op.create_index(op.f('ix_equipment_aliases_normalized_alias'), 'equipment_aliases', ['normalized_alias'], unique=False)
    op.create_table('equipment_attributes',
    sa.Column('equipment_template_id', sa.UUID(), nullable=False),
    sa.Column('attribute_name', sa.String(length=255), nullable=False),
    sa.Column('display_label', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_template_id', 'attribute_name', name='uq_attribute_name_per_template')
    )
    op.create_index(op.f('ix_equipment_attributes_equipment_template_id'), 'equipment_attributes', ['equipment_template_id'], unique=False)
    op.create_table('workbook_jobs',
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('original_file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('header_row_number', sa.Integer(), nullable=True),
    sa.Column('tag_column_number', sa.Integer(), nullable=True),
    sa.Column('equipment_column_number', sa.Integer(), nullable=True),
    sa.Column('additional_info_column_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['application_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbook_jobs_file_hash'), 'workbook_jobs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_workbook_jobs_project_code'), 'workbook_jobs', ['project_code'], unique=False)
    op.create_index(op.f('ix_workbook_jobs_status'), 'workbook_jobs', ['status'], unique=False)
    op.create_table('export_history',
    sa.Column('workbook_job_id', sa.UUID(), nullable=False),
    sa.Column('output_filename', sa.String(length=512), nullable=False),
    sa.Column('output_file_path', sa.String(length=1024), nullable=False),
    sa.Column('row_count_written', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['application_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workbook_job_id'], ['workbook_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_history_workbook_job_id'), 'export_history', ['workbook_job_id'], unique=False)
    op.create_table('imported_tag_rows',
    sa.Column('workbook_job_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('excel_row_number', sa.Integer(), nullable=False),
    sa.Column('tag_number', sa.String(length=512), nullable=True),
    sa.Column('normalized_tag_number', sa.String(length=512), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('equipment_description', sa.String(length=512), nullable=True),
    sa.Column('normalized_equipment_description', sa.String(length=512), nullable=True),
    sa.Column('equipment_template_id', sa.UUID(), nullable=True),
    sa.Column('original_additional_information', sa.Text(), nullable=True),
    sa.Column('attribute_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_additional_information', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claimed_by', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['application_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['application_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_template_id'], ['equipment_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workbook_job_id'], ['workbook_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workbook_job_id', 'sheet_name', 'excel_row_number', name='uq_tag_row_per_workbook_cell')
    )
    op.create_index(op.f('ix_imported_tag_rows_normalized_tag_number'), 'imported_tag_rows', ['normalized_tag_number'], unique=False)
    op.create_index(op.f('ix_imported_tag_rows_status'), 'imported_tag_rows', ['status'], unique=False)
    op.create_index(op.f('ix_imported_tag_rows_workbook_job_id'), 'imported_tag_rows', ['workbook_job_id'], unique=False)
    op.create_index('ix_tag_claimed_by', 'imported_tag_rows', ['claimed_by'], unique=False)
    op.create_index('ix_tag_job_equipment', 'imported_tag_rows', ['workbook_job_id', 'normalized_equipment_description'], unique=False)
    op.create_index('ix_tag_job_status', 'imported_tag_rows', ['workbook_job_id', 'status'], unique=False)
    op.create_table('tag_entry_history',
    sa.Column('imported_tag_row_id', sa.UUID(), nullable=False),
    sa.Column('attribute_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_additional_information', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['application_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imported_tag_row_id'], ['imported_tag_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_entry_history_imported_tag_row_id'), 'tag_entry_history', ['imported_tag_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_entry_history_imported_tag_row_id'), table_name='tag_entry_history')
    op.drop_table('tag_entry_history')
    op.drop_index('ix_tag_job_status', table_name='imported_tag_rows')
    op.drop_index('ix_tag_job_equipment', table_name='imported_tag_rows')
    op.drop_index('ix_tag_claimed_by', table_name='imported_tag_rows')
    op.drop_index(op.f('ix_imported_tag_rows_workbook_job_id'), table_name='imported_tag_rows')
    op.drop_index(op.f('ix_imported_tag_rows_status'), table_name='imported_tag_rows')
    op.drop_index(op.f('ix_imported_tag_rows_normalized_tag_number'), table_name='imported_tag_rows')
    op.drop_table('imported_tag_rows')
    op.drop_index(op.f('ix_export_history_workbook_job_id'), table_name='export_history')
    op.drop_table('export_history')
    op.drop_index(op.f('ix_workbook_jobs_status'), table_name='workbook_jobs')
    op.drop_index(op.f('ix_workbook_jobs_project_code'), table_name='workbook_jobs')
    op.drop_index(op.f('ix_workbook_jobs_file_hash'), table_name='workbook_jobs')
    op.drop_table('workbook_jobs')
    op.drop_index(op.f('ix_equipment_attributes_equipment_template_id'), table_name='equipment_attributes')
    op.drop_table('equipment_attributes')
    op.drop_index(op.f('ix_equipment_aliases_normalized_alias'), table_name='equipment_aliases')
    op.drop_index(op.f('ix_equipment_aliases_equipment_template_id'), table_name='equipment_aliases')
    op.drop_table('equipment_aliases')
    op.drop_index(op.f('ix_equipment_templates_normalized_description'), table_name='equipment_templates')
    op.drop_index(op.f('ix_equipment_templates_equipment_code'), table_name='equipment_templates')
    op.drop_table('equipment_templates')
    op.drop_index(op.f('ix_application_users_employee_code'), table_name='application_users')
    op.drop_table('application_users')
    # ### end Alembic commands ###
